In [1]:
import torch

In [2]:
import numpy as np

In [3]:
torch.__version__

'1.10.0'

# Part 1

In [4]:
arr = np.array([1, 2, 3, 4, 5])

In [5]:
print(arr)

[1 2 3 4 5]


In [6]:
arr.dtype

dtype('int64')

In [7]:
type(arr)

numpy.ndarray

# Convert NumPy Array to Tensor
- as_tensor()
- from_numpy()
- torch.tensor()

In [8]:
x = torch.from_numpy(arr)

In [9]:
x

tensor([1, 2, 3, 4, 5])

In [10]:
type(x)

torch.Tensor

In [11]:
torch.as_tensor(arr)

tensor([1, 2, 3, 4, 5])

In [12]:
arr2d = np.arange(0.0 , 12.0)

In [13]:
arr2d = arr2d.reshape(4,3)

In [14]:
x2 = torch.from_numpy(arr2d)

In [15]:
x2

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

### as_tensor()

In [16]:
arr[0] = 99

In [17]:
arr

array([99,  2,  3,  4,  5])

In [18]:
x

tensor([99,  2,  3,  4,  5])

In [19]:
my_arr = np.arange(0, 10) 

In [20]:
my_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
my_tensor = torch.tensor(my_arr)

In [22]:
my_other_tensor = torch.from_numpy(my_arr)

In [23]:
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
my_other_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
my_arr[0] = 9999

In [26]:
my_arr

array([9999,    1,    2,    3,    4,    5,    6,    7,    8,    9])

In [27]:
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
my_other_tensor

tensor([9999,    1,    2,    3,    4,    5,    6,    7,    8,    9])

# Part 2

In [29]:
new_arr = np.array([1, 2, 3])

In [31]:
new_arr.dtype

dtype('int64')

In [33]:
x1 = torch.tensor(new_arr)

In [37]:
x1

tensor([1, 2, 3])

In [34]:
x1.dtype

torch.int64

In [35]:
x2 = torch.Tensor(new_arr)

In [38]:
x2

tensor([1., 2., 3.])

In [36]:
x2.dtype

torch.float32

# Create placeholder
Returns a tensor filled with uninitialized data. 

In [39]:
torch.empty(2,2)

tensor([[0.0000e+00, 1.8980e+01],
        [2.3694e-38, 0.0000e+00]])

In [40]:
torch.zeros(4, 3, dtype=torch.int32)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

In [41]:
torch.ones(4, 3, dtype=torch.int32)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)

In [46]:
torch.arange(0, 18, 2)

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16])

In [48]:
torch.arange(0, 18, 2).reshape(3, 3)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [50]:
torch.linspace(0, 18, 12).reshape(3, 4)

tensor([[ 0.0000,  1.6364,  3.2727,  4.9091],
        [ 6.5455,  8.1818,  9.8182, 11.4545],
        [13.0909, 14.7273, 16.3636, 18.0000]])

# Change tensor data types

In [52]:
my_tensor = torch.tensor([1, 2, 3, 4])

In [53]:
my_tensor.dtype

torch.int64

In [56]:
my_tensor = my_tensor.type(torch.int32)

In [57]:
my_tensor.dtype

torch.int32

In [59]:
torch.rand(4, 3) # random number from uniform distribution

tensor([[0.8742, 0.1054, 0.4298],
        [0.7500, 0.4870, 0.9773],
        [0.0197, 0.6250, 0.4973],
        [0.3509, 0.2419, 0.9269]])

In [60]:
torch.randn(4, 3) # random number from normal distribution

tensor([[ 0.2494, -0.1275,  0.5286],
        [-1.5646, -0.4082,  0.5547],
        [-0.4072,  1.5852,  0.3577],
        [ 0.3726, -0.6733,  1.4878]])

In [61]:
torch.randint(low=0, high=10, size=(4, 3))

tensor([[1, 7, 3],
        [7, 8, 0],
        [7, 0, 4],
        [4, 4, 8]])

In [62]:
x = torch.zeros(2,5)

In [63]:
x

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [65]:
x.shape

torch.Size([2, 5])

In [66]:
torch.rand_like(x)

tensor([[0.6595, 0.6805, 0.0564, 0.2613, 0.9025],
        [0.7465, 0.4051, 0.9480, 0.3575, 0.7178]])

In [67]:
torch.randn_like(x)

tensor([[-1.4445, -1.2299, -1.1542, -0.8627,  1.1052],
        [-1.2905,  0.2856, -0.4649,  0.7151, -0.6382]])

In [68]:
torch.randint_like(x, low=0, high=10)

tensor([[4., 8., 2., 9., 5.],
        [6., 4., 8., 4., 3.]])

In [70]:
torch.manual_seed(42)
torch.rand(2, 4)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936]])

In [74]:
# Not the same cell with manual_seed
torch.rand(2, 4)

tensor([[0.8860, 0.5832, 0.3376, 0.8090],
        [0.5779, 0.9040, 0.5547, 0.3423]])