In [2]:
import torch
import numpy as np

# Part 1

# Indexing and Slicing

In [6]:
x = torch.arange(6).reshape(3, 2)

In [7]:
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [9]:
# tensor[row, column]
x[1,1]

tensor(3)

In [10]:
x[:,1]

tensor([1, 3, 5])

In [11]:
x[:,1:]

tensor([[1],
        [3],
        [5]])

# `view()` and `reshape()`

In [12]:
x = torch.arange(10)

In [13]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
x.view(2, 5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [15]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
x.reshape(2, 5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [17]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
x = x.reshape(2, 5)

In [19]:
x

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [26]:
x = torch.arange(10)

In [27]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
z = x.view(2, 5)

In [29]:
z

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [30]:
x[0] = 9999

In [31]:
x

tensor([9999,    1,    2,    3,    4,    5,    6,    7,    8,    9])

In [32]:
z

tensor([[9999,    1,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [33]:
x = torch.arange(10)

In [34]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
x.shape

torch.Size([10])

In [37]:
# INFER what the 2nd dimension
x.view(2, -1)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [38]:
x.view(-1, 5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

# Tensor Arithmetic

In [39]:
a = torch.tensor([1., 2., 3.])

In [40]:
b = torch.tensor([4., 5., 6.])

In [42]:
a.dtype

torch.float32

In [43]:
b.dtype

torch.float32

In [44]:
a + b

tensor([5., 7., 9.])

In [45]:
torch.add(a, b)

tensor([5., 7., 9.])

In [47]:
a.mul(b)

tensor([ 4., 10., 18.])

In [48]:
a

tensor([1., 2., 3.])

In [49]:
# Reassign

a.mul_(b)

tensor([ 4., 10., 18.])

In [50]:
a

tensor([ 4., 10., 18.])

# Part 2

In [51]:
a = torch.tensor([1., 2., 3.])

In [52]:
a

tensor([1., 2., 3.])

In [53]:
b

tensor([4., 5., 6.])

In [54]:
a * b

tensor([ 4., 10., 18.])

# Dot product

In [55]:
a.dot(b)

tensor(32.)

# Matrix Multiplication

In [56]:
a = torch.tensor([[0, 2, 4], [1, 3, 5]])

In [57]:
a

tensor([[0, 2, 4],
        [1, 3, 5]])

In [58]:
b = torch.tensor([[6,7], [8,9], [10,11]])

In [59]:
a.shape

torch.Size([2, 3])

In [62]:
b.shape



torch.Size([3, 2])

In [63]:
torch.mm(a, b)

tensor([[56, 62],
        [80, 89]])

In [64]:
a @ b

tensor([[56, 62],
        [80, 89]])

# Euclidian Norm or L2
magnitude of vector

In [66]:
x = torch.tensor([2., 3., 4., 5.])

In [67]:
x

tensor([2., 3., 4., 5.])

In [68]:
x.norm()

tensor(7.3485)

In [69]:
x.numel()

4

In [70]:
len(x)

4

In [71]:
len(a)

2

In [73]:
a.numel()

6